# Generated by Django 6.0.6 on 2026-06-20 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('strategy_name', models.CharField(db_index=True, max_length=128)),
                ('stock_code', models.CharField(db_index=True, max_length=32)),
                ('parameters', models.JSONField(default=dict)),
                ('engine', models.JSONField(default=dict)),
                ('data_info', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('sharpe', models.FloatField(default=0)),
                ('cagr', models.FloatField(default=0)),
                ('max_drawdown', models.FloatField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='analysis.analysisreport')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
