# Generated by Django 6.0.6 on 2026-06-20 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_code', models.CharField(db_index=True, max_length=32)),
                ('stock_name', models.CharField(default='', max_length=128)),
                ('is_sector', models.BooleanField(default=False)),
                ('sector_type', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('final_state', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('config_snapshot', models.JSONField(default=dict)),
                ('query', models.CharField(blank=True, default='', max_length=256)),
                ('legacy_filename', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisNodeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('node', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('error', 'Error')], default='completed', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analysis.analysisreport')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('report', 'seq')},
            },
        ),
    ]
