# Generated by Django 6.0.6 on 2026-08-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='sector_cons',
            field=models.JSONField(default=list),
        ),
    ]
