# Generated by Django 6.0.6 on 2026-08-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_add_sector_cons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('awaiting_approval', 'Awaiting Approval'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
