/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/core/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Returns 200 if the API is up.
         */
        get: operations["backend_core_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Return the merged config. api_key is masked (has_api_key flag instead).
         */
        get: operations["backend_configapp_api_get_config"];
        /**
         * Update Config
         * @description Update non-secret config (+ optional api_key). Persists to config_user.json.
         */
        put: operations["backend_configapp_api_update_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description List supported models for the dropdown.
         */
        get: operations["backend_configapp_api_list_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/indices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indices
         * @description Major market index quotes.
         */
        get: operations["backend_market_api_indices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/hot-sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hot Sectors
         * @description Leading industry sectors.
         */
        get: operations["backend_market_api_hot_sectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/sentiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sentiment
         * @description Market breadth + sentiment label.
         */
        get: operations["backend_market_api_sentiment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Endpoint
         * @description Resolve a query to a stock code or board (sector).
         */
        get: operations["backend_market_api_search_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/cache/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cache Status
         * @description AkShare cache status.
         */
        get: operations["backend_market_api_cache_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cache Clear
         * @description Clear expired AkShare cache entries.
         */
        delete: operations["backend_market_api_cache_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Market News
         * @description 同花顺实时新闻.
         */
        get: operations["backend_market_api_market_news"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analysis List
         * @description Paginated analysis history list (lightweight).
         */
        get: operations["backend_analysis_api_analysis_list"];
        put?: never;
        /**
         * Create Analysis
         * @description Create an AnalysisReport, resolve the entity, and start the graph run.
         *
         *     Returns 202 with the job_id immediately; the client then opens the SSE
         *     stream at GET /{job_id}/stream.
         */
        post: operations["backend_analysis_api_create_analysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analysis Stream
         * @description Server-Sent Events stream of node-by-node progress.
         *
         *     Supports Last-Event-ID / ?resume_from=<seq> for reconnect.
         *     Emits:
         *         event: node\ndata: {"seq":N,"node":"...","status":"completed|error","message":"..."}
         *         event: done\ndata: {"report_id":"..."}
         *         event: error\ndata: {"node":"...","message":"..."}
         *
         *     Must be an async view: with a sync view Django buffers the whole async
         *     generator (async_to_sync(to_list)) and the stream arrives only when the
         *     analysis finishes.
         */
        get: operations["backend_analysis_api_analysis_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analysis Detail
         * @description Full AnalysisReport (status + final_state).
         */
        get: operations["backend_analysis_api_analysis_detail"];
        put?: never;
        post?: never;
        /**
         * Analysis Delete
         * @description Delete an analysis report (and its node events via cascade).
         */
        delete: operations["backend_analysis_api_analysis_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{job_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analysis Approval
         * @description Human-in-the-loop: deliver the approval verdict to a paused worker.
         *
         *     The worker is blocked at the approval gate (report status
         *     "awaiting_approval"); this wakes it with {"approved", "comment"}.
         *     Returns 404 for unknown jobs and 409 when nobody is awaiting approval.
         */
        post: operations["backend_analysis_api_analysis_approval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtest List
         * @description Paginated backtest history (lightweight rows, no JSON blobs).
         */
        get: operations["backend_backtests_api_backtest_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtest Detail
         * @description Full record incl. parameters / engine / data_info / metrics JSON.
         */
        get: operations["backend_backtests_api_backtest_detail"];
        put?: never;
        post?: never;
        /**
         * Backtest Delete
         * @description Delete a record from the history.
         */
        delete: operations["backend_backtests_api_backtest_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ConfigOut */
        ConfigOut: {
            /**
             * Api Base
             * @default
             */
            api_base: string;
            /**
             * Api Key
             * @default
             */
            api_key: string;
            /**
             * Has Api Key
             * @default false
             */
            has_api_key: boolean;
            /**
             * Model Name
             * @default
             */
            model_name: string;
            /**
             * Supported Models
             * @default []
             */
            supported_models: string[];
            /**
             * Llm
             * @default {}
             */
            llm: {
                [key: string]: unknown;
            };
            /**
             * Backtest
             * @default {}
             */
            backtest: {
                [key: string]: unknown;
            };
            /**
             * Web
             * @default {}
             */
            web: {
                [key: string]: unknown;
            };
        };
        /** ConfigIn */
        ConfigIn: {
            /** Api Key */
            api_key?: string | null;
            /** Api Base */
            api_base?: string | null;
            /** Model Name */
            model_name?: string | null;
            /** Supported Models */
            supported_models?: string[] | null;
            /** Llm */
            llm?: {
                [key: string]: unknown;
            } | null;
            /** Backtest */
            backtest?: {
                [key: string]: unknown;
            } | null;
        };
        /** ModelsOut */
        ModelsOut: {
            /** Supported Models */
            supported_models: string[];
        };
        /** SearchOut */
        SearchOut: {
            /** Type */
            type: string;
            /** Stock Code */
            stock_code?: string | null;
            /** Stock Name */
            stock_name?: string | null;
            /**
             * Is Sector
             * @default false
             */
            is_sector: boolean;
            /**
             * Sector Type
             * @default
             */
            sector_type: string;
            /**
             * Sector Cons
             * @default []
             */
            sector_cons: unknown[];
        };
        /** CacheStatusOut */
        CacheStatusOut: {
            /** Cache File */
            cache_file?: string | null;
            /** Cache Size */
            cache_size?: number | null;
            /** Data Sources */
            data_sources?: {
                [key: string]: unknown;
            } | null;
        };
        /** AnalysisCreateOut */
        AnalysisCreateOut: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Stock Code */
            stock_code: string;
            /** Stock Name */
            stock_name: string;
            /** Is Sector */
            is_sector: boolean;
        };
        /** AnalysisCreateIn */
        AnalysisCreateIn: {
            /** Query */
            query: string;
        };
        /** AnalysisListItem */
        AnalysisListItem: {
            /** Id */
            id: string;
            /** Stock Code */
            stock_code: string;
            /** Stock Name */
            stock_name: string;
            /** Is Sector */
            is_sector: boolean;
            /** Status */
            status: string;
            /**
             * Error
             * @default
             */
            error: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** AnalysisDetailOut */
        AnalysisDetailOut: {
            /** Id */
            id: string;
            /**
             * Query
             * @default
             */
            query: string;
            /** Stock Code */
            stock_code: string;
            /** Stock Name */
            stock_name: string;
            /** Is Sector */
            is_sector: boolean;
            /**
             * Sector Type
             * @default
             */
            sector_type: string;
            /** Status */
            status: string;
            /**
             * Error
             * @default
             */
            error: string;
            /**
             * Final State
             * @default {}
             */
            final_state: {
                [key: string]: unknown;
            };
            /**
             * Config Snapshot
             * @default {}
             */
            config_snapshot: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ApprovalIn */
        ApprovalIn: {
            /**
             * Approved
             * @default true
             */
            approved: boolean;
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /** BacktestListOut */
        BacktestListOut: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Strategy Name */
            strategy_name: string;
            /** Stock Code */
            stock_code: string;
            /** Sharpe */
            sharpe: number;
            /** Cagr */
            cagr: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Win Rate */
            win_rate: number;
            /** Report Id */
            report_id?: string | null;
            /** Timestamp */
            timestamp: string;
        };
        /** BacktestPageOut */
        BacktestPageOut: {
            /** Items */
            items: components["schemas"]["BacktestListOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** BacktestDetailOut */
        BacktestDetailOut: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Strategy Name */
            strategy_name: string;
            /** Stock Code */
            stock_code: string;
            /** Sharpe */
            sharpe: number;
            /** Cagr */
            cagr: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Win Rate */
            win_rate: number;
            /** Report Id */
            report_id?: string | null;
            /** Timestamp */
            timestamp: string;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Engine */
            engine: {
                [key: string]: unknown;
            };
            /** Data Info */
            data_info: {
                [key: string]: unknown;
            };
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    backend_core_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    backend_configapp_api_get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    backend_configapp_api_update_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    backend_configapp_api_list_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsOut"];
                };
            };
        };
    };
    backend_market_api_indices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    backend_market_api_hot_sectors: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    backend_market_api_sentiment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    backend_market_api_search_endpoint: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
        };
    };
    backend_market_api_cache_status: {
        parameters: {
            query?: {
                stock_code?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheStatusOut"];
                };
            };
        };
    };
    backend_market_api_cache_clear: {
        parameters: {
            query?: {
                ttl_seconds?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    backend_market_api_market_news: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    backend_analysis_api_analysis_list: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                stock_code?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisListItem"][];
                };
            };
        };
    };
    backend_analysis_api_create_analysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisCreateIn"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisCreateOut"];
                };
            };
        };
    };
    backend_analysis_api_analysis_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    backend_analysis_api_analysis_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetailOut"];
                };
            };
        };
    };
    backend_analysis_api_analysis_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    backend_analysis_api_analysis_approval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    backend_backtests_api_backtest_list: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                strategy_name?: string | null;
                stock_code?: string | null;
                report_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestPageOut"];
                };
            };
        };
    };
    backend_backtests_api_backtest_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestDetailOut"];
                };
            };
        };
    };
    backend_backtests_api_backtest_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
